import type { Category } from "../types/category";

export interface IntentRule {
  category: Category;
  // 입력 문자열에 (소문자 기준 substring) 포함되면 매칭으로 간주
  keywords: string[];
}

// 카테고리별 키워드 룰. "넓은 의미"의 카테고리 정의를 따라 키워드도 폭넓게.
// 매칭은 단순 substring(toLowerCase) 기준이라 의도적으로 짧은 토큰을 피해 오탐 줄임.
export const INTENT_RULES: IntentRule[] = [
  {
    category: "bugfix",
    keywords: [
      "버그",
      "오류",
      "에러",
      "안 되",
      "안돼",
      "안 됨",
      "안됨",
      "동작 안",
      "작동 안",
      "깨져",
      "깨짐",
      "무한루프",
      "무한 루프",
      "크래시",
      "충돌",
      "되지 않",
      "망가",
      "먹통",
      "이슈",
      "bug",
      "error",
      "broken",
      "crash",
      "issue",
      "fix",
      "failing",
      "not working",
    ],
  },
  {
    category: "refactor",
    keywords: [
      "리팩",
      "리팩터링",
      "리팩토링",
      "구조 개선",
      "구조개선",
      "코드 정리",
      "코드정리",
      "중복 제거",
      "중복제거",
      "가독성",
      "추출",
      "분리해",
      "쪼개",
      "refactor",
      "refactoring",
      "restructure",
      "extract",
      "cleanup",
      "clean up",
      "deduplicate",
      "simplify",
    ],
  },
  {
    category: "backend",
    keywords: [
      "api",
      "엔드포인트",
      "라우트",
      "컨트롤러",
      "서비스 레이어",
      "인증 api",
      "로그인 api",
      "회원가입 api",
      "토큰",
      "jwt",
      "세션",
      "데이터베이스",
      "디비",
      "db",
      "쿼리",
      "스키마",
      "미들웨어",
      "권한",
      "서버",
      "endpoint",
      "route",
      "controller",
      "auth",
      "login",
      "signup",
      "register",
      "session",
      "middleware",
      "database",
      "query",
      "crud",
      "rest",
      "graphql",
      "orm",
    ],
  },
  {
    category: "frontend",
    keywords: [
      "히어로",
      "카드",
      "네비게이션",
      "네비",
      "헤더",
      "푸터",
      "모달",
      "폼 ",
      "버튼",
      " ui",
      "ui ",
      "ux",
      "컴포넌트",
      "페이지",
      "화면",
      "메뉴",
      "사이드바",
      "인터랙션",
      "애니메이션",
      "반응형",
      "디자인",
      "스타일",
      "레이아웃",
      "리스트",
      "테이블",
      "드롭다운",
      "탭 ",
      "캐러셀",
      "슬라이더",
      "아이콘",
      "다크모드",
      "라이트모드",
      "hero",
      "card",
      "navigation",
      "navbar",
      "header",
      "footer",
      "modal",
      "form",
      "button",
      "component",
      "page",
      "screen",
      "menu",
      "sidebar",
      "animation",
      "responsive",
      "design",
      "style",
      "layout",
      "dropdown",
      "tab",
      "carousel",
      "slider",
      "icon",
    ],
  },
];

// 동점 시 적용할 우선순위.
// 명시적 의도 신호(bugfix/refactor)가 있으면 frontend/backend 키워드보다 우선.
export const PRIORITY_ORDER: Category[] = [
  "bugfix",
  "refactor",
  "backend",
  "frontend",
];
